### ISSUE TITLE
command line executor runner

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/mirakuru#24]
Add command-line executor runner, that will be able to start and run processes defined in config file.

For example, having a mirakuru.yaml defined:

``` yaml
my_process:
    executor: Executor
    params: ....
database:
    executor: TCPExecutor
    command: postgresql
    host: localhost
    port: port
```

it should be possible to run just `mirakuru mirakuru.yaml` to start defined processes.

Maintaining of order of these processes will be required!
